# Generated by Django 2.1.2 on 2018-10-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.Activity', verbose_name='activity')),
                ('fiscal_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.FiscalPosition', verbose_name='fiscal position')),
            ],
        ),
    ]
